version: '3'
services:
  frontend:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    container_name: client-container
    networks:
      - mern-stack-network
    volumes:
      - ./client:/app
    depends_on:
      - backend

  backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: server-container
    networks:
      - mern-stack-network
    volumes:
      - ./server:/app
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres-container
    networks:
      - mern-stack-network
    ports:
      - "5432:5432"
    volumes:
      database:
        image: postgres
        container_name: postgres-container
        networks:
          - mern-stack-network
        ports:
          - "5432:5432"
        volumes:
          - postgres-data:/db/data
    environment:
      - POSTGRES_USER="default"
      - POSTGRES_PASSWORD="yclBRTw4N1sS"
      - POSTGRES_DATABASE="verceldb"

networks:
  mern-stack-network:
volumes:
  postgres-data: